from local_ai.infrastructure.openvino.whisper import (
    WhisperRuntime,
    build_generate_kwargs,
    create_whisper_runtime,
    likely_reason_details,
)
from local_ai.shared.domain.devices import (
    DEFAULT_DEVICE_ORDER,
    DeviceSelection,
    parse_device_preference,
    pick_first_available_device,
    query_available_devices,
    resolve_device_selection,
)
from local_ai.shared.domain.errors import DeviceListRequested, PipelineSetupError
from local_ai.shared.domain.models import (
    DEFAULT_MODEL_FOR_DEVICE,
    DEFAULT_MODEL_REPO_FOR_DEVICE,
    ModelArtifact,
    REQUIRED_OPENVINO_WHISPER_FILES,
    download_openvino_model as _download_openvino_model,
    hf_cache_root as _hf_cache_root,
    huggingface_token,
    is_openvino_whisper_dir,
    missing_openvino_whisper_files,
    resolve_cached_openvino_model as _resolve_cached_openvino_model,
    resolve_model_artifact,
    resolve_model_dir,
)

__all__ = [
    "DEFAULT_DEVICE_ORDER",
    "DEFAULT_MODEL_FOR_DEVICE",
    "DEFAULT_MODEL_REPO_FOR_DEVICE",
    "REQUIRED_OPENVINO_WHISPER_FILES",
    "DeviceListRequested",
    "DeviceSelection",
    "ModelArtifact",
    "PipelineSetupError",
    "WhisperRuntime",
    "_download_openvino_model",
    "_hf_cache_root",
    "_resolve_cached_openvino_model",
    "build_generate_kwargs",
    "create_whisper_runtime",
    "huggingface_token",
    "is_openvino_whisper_dir",
    "likely_reason_details",
    "missing_openvino_whisper_files",
    "parse_device_preference",
    "pick_first_available_device",
    "query_available_devices",
    "resolve_device_selection",
    "resolve_model_artifact",
    "resolve_model_dir",
]
